# Generated by Django 2.2.13 on 2020-06-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divideflats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuaciones', models.CharField(max_length=250)),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divideflats.Piso')),
            ],
        ),
    ]
