# Generated by Django 2.2.13 on 2020-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divideflats', '0002_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='piso',
            name='habitaciones',
            field=models.CharField(default='', max_length=40),
        ),
    ]
